version: '3.8'

services:
  flaskproject:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flaskapi
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=8080"]
    depends_on:
      - mongodb
    networks:
      - api

  mongodb:
    image: mongo:latest
    container_name: mongo_flask
    restart: unless-stopped
    command: mongod --logpath /var/log/mongodb/mongod.log
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    env_file:
      - .env
    networks:
      - api

networks:
  api:
volumes:
  mongodb_data: